# Generated by Django 5.2.12 on 2026-03-22 04:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('product_type', models.CharField(choices=[('tshirt', 'T-shirt'), ('hoodie', 'Hoodie'), ('pant', 'Pant'), ('shirt', 'Shirt'), ('skirt', 'Skirt'), ('jacket', 'Jacket')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional name for this saved design.', max_length=200)),
                ('fabric', models.CharField(choices=[('cotton', 'Cotton'), ('silk', 'Silk'), ('denim', 'Denim'), ('wool', 'Wool'), ('linen', 'Linen'), ('polyester', 'Polyester')], max_length=30)),
                ('part_colors', models.JSONField(default=dict, help_text='Map part name to hex color, e.g. {"body": "#222222", "sleeves": "#eeeeee"}.')),
                ('size', models.CharField(help_text='Preset size label: S, M, L, XL, or CUSTOM when using custom measurements.', max_length=10)),
                ('custom_size', models.CharField(blank=True, help_text='Free text when size is CUSTOM (measurements or notes).', max_length=120)),
                ('pattern', models.CharField(choices=[('plain', 'Plain'), ('check_line', 'Check line')], max_length=20)),
                ('has_collar', models.BooleanField(default=False)),
                ('sleeve_style', models.CharField(choices=[('full', 'Full sleeve'), ('half', 'Half sleeve'), ('none', 'No sleeves')], max_length=10)),
                ('has_pocket', models.BooleanField(default=False)),
                ('pocket_position', models.CharField(blank=True, help_text='e.g. left_chest, right_hip — used when has_pocket is true.', max_length=50)),
                ('has_hoodie', models.BooleanField(default=False)),
                ('pant_length', models.CharField(blank=True, choices=[('half', 'Half pant'), ('full', 'Full pant')], help_text='Relevant for pants; optional for other product types.', max_length=10)),
                ('neck_design', models.CharField(blank=True, choices=[('crew', 'Crew neck'), ('v_neck', 'V-neck'), ('polo', 'Polo collar'), ('boat', 'Boat neck'), ('scoop', 'Scoop neck'), ('turtleneck', 'Turtleneck')], max_length=30)),
                ('custom_design', models.ImageField(blank=True, help_text='Optional uploaded artwork.', null=True, upload_to='custom_designs/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customizations', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customizations', to='shop.product')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('shipping_address', models.TextField()),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('customization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shop.customization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-placed_at'],
            },
        ),
    ]
