# Generated by Django 4.2.29 on 2026-04-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_status_quality_check_packed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_part_colors',
            field=models.JSONField(blank=True, default=dict, help_text='Optional map of part keys to #hex defaults for the customize UI, e.g. {"body":"#f5f5f5","sleeves":"#1a1a1a"}.'),
        ),
    ]
