# Generated by Django 4.2.29 on 2026-04-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_default_part_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_fabric',
            field=models.CharField(default='cotton', help_text='Fabric shown with this garment in the catalog; used as the customize form default.', max_length=30),
        ),
    ]
