/** Shared inline styles for admin sub-pages (tables, actions). */
export const adminSharedStyles = {
  panel: {
    background: "#fff",
    borderRadius: "14px",
    border: "1px solid #e6e8f0",
    padding: "24px",
  },
  muted: { color: "#51607a", padding: "8px 0" },
  heading: { margin: "0 0 8px", color: "#1a1a2e", fontSize: "20px" },
  error: { marginTop: "12px", color: "#b91c1c", fontSize: "15px" },
  tableCard: {
    border: "1px solid #e6e8f0",
    borderRadius: "14px",
    overflowX: "auto",
    background: "#fff",
    boxShadow: "0 8px 24px rgba(26, 26, 46, 0.04)",
  },
  tableTitle: {
    margin: 0,
    padding: "16px 16px 0",
    color: "#1a1a2e",
    fontSize: "16px",
    fontWeight: 800,
  },
  tableHint: {
    margin: "6px 0 0",
    padding: "0 16px",
    fontSize: "12px",
    color: "#64748b",
    lineHeight: 1.4,
  },
  userActionBanner: {
    margin: "10px 16px 0",
    padding: "8px 12px",
    fontSize: "13px",
    color: "#1e40af",
    background: "#eff6ff",
    borderRadius: "8px",
    border: "1px solid #bfdbfe",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    marginTop: "10px",
  },
  th: {
    textAlign: "left",
    fontSize: "12px",
    color: "#5e6880",
    borderBottom: "1px solid #e6e8f0",
    padding: "10px 14px",
    whiteSpace: "nowrap",
  },
  td: {
    textAlign: "left",
    fontSize: "13px",
    color: "#1c2438",
    borderBottom: "1px solid #eef1f8",
    padding: "10px 14px",
    whiteSpace: "nowrap",
  },
  tdActions: {
    textAlign: "left",
    fontSize: "13px",
    color: "#1c2438",
    borderBottom: "1px solid #eef1f8",
    padding: "10px 14px",
    verticalAlign: "middle",
    whiteSpace: "normal",
  },
  rowInactive: { opacity: 0.85 },
  statusActive: {
    fontSize: "12px",
    fontWeight: 700,
    color: "#15803d",
  },
  statusBlocked: {
    fontSize: "12px",
    fontWeight: 700,
    color: "#b91c1c",
  },
  actionBtns: { display: "flex", flexWrap: "wrap", gap: "8px", alignItems: "center" },
  actionMuted: { fontSize: "12px", color: "#94a3b8" },
  btnSecondary: {
    fontSize: "12px",
    fontWeight: 700,
    padding: "6px 12px",
    borderRadius: "8px",
    border: "1px solid #cbd5e1",
    background: "#fff",
    color: "#334155",
    cursor: "pointer",
  },
  btnWarn: {
    fontSize: "12px",
    fontWeight: 700,
    padding: "6px 12px",
    borderRadius: "8px",
    border: "1px solid #fcd34d",
    background: "#fffbeb",
    color: "#b45309",
    cursor: "pointer",
  },
  btnDanger: {
    fontSize: "12px",
    fontWeight: 700,
    padding: "6px 12px",
    borderRadius: "8px",
    border: "1px solid #fecaca",
    background: "#fef2f2",
    color: "#b91c1c",
    cursor: "pointer",
  },
  summaryRow: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: "16px",
    marginBottom: "20px",
  },
  statCard: {
    background: "#fff",
    borderRadius: "14px",
    border: "1px solid #e6e8f0",
    boxShadow: "0 8px 24px rgba(26, 26, 46, 0.06)",
    padding: "18px 20px",
  },
  statLabel: {
    margin: 0,
    fontSize: "12px",
    color: "#64748b",
    fontWeight: 600,
  },
  statValue: {
    margin: "8px 0 0",
    fontSize: "22px",
    fontWeight: 800,
    color: "#1a1a2e",
    lineHeight: 1.1,
  },
};
